// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCowqWfToZg5d2cdbNVGfQ51tIyMGtBOwI',
    appId: '1:92305610778:web:a4569729d046a18a3819a3',
    messagingSenderId: '92305610778',
    projectId: 'order-tracker-9adc4',
    authDomain: 'order-tracker-9adc4.firebaseapp.com',
    storageBucket: 'order-tracker-9adc4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcu_wRhbpa8T1pk-0uBRgDZ7QCMi1fWOI',
    appId: '1:92305610778:android:f7afd1f23bd5ff343819a3',
    messagingSenderId: '92305610778',
    projectId: 'order-tracker-9adc4',
    storageBucket: 'order-tracker-9adc4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNjis4z9wfOxGagdYEj4ZlJydVExtWjLc',
    appId: '1:92305610778:ios:a888224c42f52b1a3819a3',
    messagingSenderId: '92305610778',
    projectId: 'order-tracker-9adc4',
    storageBucket: 'order-tracker-9adc4.appspot.com',
    iosBundleId: 'com.example.orderTracker',
  );
}
